name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]

    env:
      USING_COVERAGE: "3.9"

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.4"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install isort black coverage flake8 flit mccabe mypy pytest tox tox-gh-actions
      - name: Run tox
        run: |
          python -m tox
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          files: ./coverage.xml