name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'blog/*'
      - 'resume/*'
      - 'rbo_django/*'
      - 'scripts/*'
      - 'tests/*'
  pull_request:
    branches: [ main ]
    paths:
      - 'blog/*'
      - 'resume/*'
      - 'rbo_django/*'
      - 'scripts/*'
      - 'tests/*'
  workflow_dispatch:

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry
          poetry install -vvv

      - name: Run pytest and collect coverage
        run: |
            poetry run pytest -ra -v --cov=blog --cov=resume --cov=rbo_django --cov-report xml .


      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          files: ./coverage.xml
